### ISSUE TITLE
설명 파일 추가

### ISSUE THREAD

**Issue by kyle-seongwoo-jun** [FuZer/Study_TensorFlow#5]
각 파일이나 세션마다 그에 관한 설명을 담은 md 파일이 있으면 좋겠습니다.... ㅜㅠ

**Comment by FuZer** [comment]
우선 이 레포는 [공식 레포](https://github.com/hunkim/DeepLearningZeroToAll)가 올라옴에 따라 작업이 종료되었다는 점을 말씀드립니다. 
현재 [공식 레포](https://github.com/hunkim/DeepLearningZeroToAll) 에서 ipynb 형식의 파일로 각 코드마다 설명을 추가하는 작업을 제가 진행 중에 있습니다. (게을러서 작업이 지연되고 있습니다만..)   추후에 [공식 레포](https://github.com/hunkim/DeepLearningZeroToAll) 에 올라오는 파일을 확인 하시면 될듯하고 

현재 제가 작업중인 레포를 올려드립니다. [링크](https://github.com/FuZer/DeepLearningZeroToAll/tree/ipynb/ipynb)

**Comment by kyle-seongwoo-jun** [comment]
@FuZer 감사합니다 😄
